# -*- coding: utf-8 -*-
"""KPI Law Guide.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hg9kSlIO4MAe23RzRb8OtzAKGL77P-xR
"""

#!/usr/bin/env python3
"""
EU Non-Price KPI Tender Law Guide — Detailed Edition
----------------------------------------------------
A command-line guide that explains the EU legal framework for non-price
criteria in renewable tenders, with a special focus on offshore wind.

This version keeps the same menu structure as the earlier script, but gives
much richer explanations for each law and each KPI-related option so that a
user can understand the theory without reading the legal text first.

Important note:
This guide is educational and thesis-oriented. The official legal text always
prevails over this summary.
"""

from dataclasses import dataclass
from textwrap import fill
import os


@dataclass
class Topic:
    title: str
    body: str
    links: list[str]


WRAP = 100


def clear_screen() -> None:
    os.system("cls" if os.name == "nt" else "clear")


def print_block(text: str) -> None:
    for paragraph in text.strip().split("\n\n"):
        print(fill(paragraph.strip(), WRAP))
        print()


def print_topic(topic: Topic) -> None:
    clear_screen()
    print("=" * WRAP)
    print(topic.title)
    print("=" * WRAP)
    print()
    print_block(topic.body)
    print("Official links:")
    for link in topic.links:
        print(f" - {link}")
    print()
    input("Press Enter to go back...")


MAIN_MENU = {
    "1": "Most relevant original laws",
    "2": "Laws that control auction design",
    "3": "Laws that feed KPI content",
    "4": "Extra offshore-specific EU laws",
    "5": "Future law: Accelerator Act",
}


SECTION_INTROS = {
    "1": """
    This section contains the three laws that matter most if someone is trying
    to understand the EU non-price tender system from the top down. The right
    reading order is usually: first NZIA, then Implementing Regulation
    2025/1176, then Implementing Regulation 2025/1178. In simple terms, NZIA
    creates the legal obligation, 2025/1176 explains the KPI framework, and
    2025/1178 gives the detailed product/component list needed for resilience.
    """,
    "2": """
    This section is about tender architecture. These laws do not create all 12
    KPI families, but they decide how renewable support schemes, competitive
    bidding, contracts for difference, state aid compatibility, procurement
    logic, and concession structures must work. In practice, these rules decide
    how far a Member State can go when it adds non-price criteria to a tender.
    """,
    "3": """
    This section explains where the content of the KPI families comes from.
    Many KPIs in Implementing Regulation 2025/1176 are not built from zero.
    Instead, they borrow their substance from EU law on sustainability,
    corporate due diligence, cybersecurity, customs origin, product design,
    environmental protection, and lifecycle methods.
    """,
    "4": """
    This section is especially useful for offshore wind. These laws do not form
    a separate offshore KPI code, but they shape where projects can be located,
    how environmental assessment works, and why offshore policy has moved toward
    resilience, sustainability, and strategic supply-chain thinking.
    """,
    "5": """
    This section is about the future-looking Industrial Accelerator Act. It is
    relevant if you want to discuss where EU industrial policy may go next, but
    it should not be confused with the current binding legal basis for
    non-price KPIs in renewable tenders.
    """,
}


SUB_MENUS = {
    "1": {
        "1": "NZIA",
        "2": "Implementing Regulation 2025/1176",
        "3": "Implementing Regulation 2025/1178",
    },
    "2": {
        "1": "RED / RED III",
        "2": "Electricity market reform",
        "3": "CEEAG 2022",
        "4": "Procurement and concession directives",
    },
    "3": {
        "1": "Responsible business conduct",
        "2": "Cybersecurity and data security",
        "3": "Ability to deliver fully and on time",
        "4": "Resilience",
        "5": "Carbon / circular economy / efficiency / pollution",
        "6": "Biodiversity / water / offshore environment",
    },
    "4": {
        "1": "Maritime Spatial Planning Directive",
        "2": "SEA and EIA",
        "3": "Offshore strategy and wind action plan",
    },
    "5": {
        "1": "Industrial Accelerator Act",
    },
}


TOPICS = {
    "1": {
        "1": Topic(
            "Regulation (EU) 2024/1735 — Net-Zero Industry Act (NZIA)",
            """
            What it is:
            NZIA is the main EU law that changed non-price criteria from a policy
            choice into a legal obligation in part of the renewable auction
            system. For your thesis topic, Article 26 is the central provision.
            It is the legal reason why Member States now have to think seriously
            about non-price criteria in renewable tenders instead of treating
            them as optional extras.

            Main purpose:
            The law is trying to do more than deploy renewable energy at the
            lowest immediate price. It also tries to strengthen EU clean-tech
            manufacturing, reduce strategic dependency on overly concentrated
            third-country supply chains, improve delivery reliability, and bring
            sustainability, resilience, and innovation into access-to-market
            rules. So NZIA sits at the intersection of energy policy and
            industrial policy.

            Core legal effect for auctions:
            Article 26 says that for the renewable technologies covered by the
            act, Member States must include three mandatory pre-qualification
            criteria in relevant auctions: responsible business conduct,
            cybersecurity and data security, and ability to deliver the project
            fully and on time. On top of that, auctions must also contribute to
            resilience and to at least one additional area: environmental
            sustainability beyond legal minimums, innovation, or energy-system
            integration.

            Weighting logic:
            When sustainability and resilience are used as award criteria, NZIA
            sets a minimum weight of 5 percent for each such criterion and a
            combined weight between 15 percent and 30 percent of the total award
            criteria. This matters because it means non-price criteria cannot be
            purely symbolic if they are chosen as scoring criteria.

            Scope and escape valve:
            The rules apply to at least 30 percent of the yearly auction volume
            in each Member State, or alternatively at least 6 GW per year. At
            the same time, NZIA gives Member States a cost-based safeguard:
            where applying the criteria would create disproportionate costs,
            estimated differences above 15 percent per auction may be presumed
            disproportionate if based on objective and verifiable data.

            Relationship with other EU law:
            NZIA does not operate alone. It says its auction rules are without
            prejudice to RED, State aid rules, and the Union's international
            obligations. That is why in practice you always have to read NZIA
            together with RED, CEEAG, and sometimes procurement law.

            Offshore wind relevance:
            Offshore wind does not have its own standalone EU KPI code. Instead,
            offshore auctions sit inside this general NZIA architecture. That
            means offshore projects are legally drawn into the same EU logic on
            resilience, sustainability, delivery readiness, and non-price tender
            design, even though national offshore tenders may add extra detail.

            Common misunderstanding:
            A common mistake is to think NZIA already tells you exactly how to
            score every KPI. It does not. NZIA is the framework law. It tells
            Member States what they must include, what the basic weighting logic
            is, and what policy goals the auction should serve. The detailed KPI
            content is then developed in Implementing Regulation 2025/1176.

            Why this law matters most:
            If someone understands only one EU law in this area, it should be
            NZIA Article 26, because it is the legal doorway through which the
            entire non-price tender discussion entered the renewable auction
            system.
            """,
            ["https://eur-lex.europa.eu/eli/reg/2024/1735/oj/eng"],
        ),
        "2": Topic(
            "Commission Implementing Regulation (EU) 2025/1176",
            """
            What it is:
            This is the central implementing act for renewable-auction KPIs. It
            was adopted because NZIA required the Commission to further specify
            the pre-qualification and award criteria under Article 26. In simple
            words, NZIA says non-price criteria must be used, while Regulation
            2025/1176 explains how they can actually be designed and assessed.

            Main purpose:
            Its purpose is operational clarity. Without this act, Member States
            would have had the obligation to use non-price criteria but no common
            EU-level method for defining them. The regulation therefore turns
            broad political categories into a usable legal framework for tender
            authorities and bidders.

            What it contains:
            The regulation covers the three mandatory pre-qualification criteria:
            responsible business conduct in Article 4, cybersecurity and data
            security in Article 5, and ability to deliver fully and on time in
            Article 6. It then moves to resilience in Article 7 and to the
            sustainability contribution in Articles 8 to 15. Those sustainability
            articles cover carbon footprint, circular economy, biodiversity
            impact, energy efficiency, water use and water protection, pollution,
            innovation, and energy-system integration.

            Why this matters for KPI design:
            This act is the real bridge between law and quantification. It tells
            authorities what kind of evidence they may request, which external EU
            laws they should rely on, when methodologies should come from Union
            law and when international standards may be used, and when criteria
            can be pre-qualification, award criteria, or a combination of both.

            Assessment, scoring, and compliance:
            Articles 16 and 17 are especially important. They require authorities
            to use a transparent, objective, and non-discriminatory methodology
            to assess the chosen non-price criteria. Where possible, scoring
            should be quantitative and published in advance. The act also allows
            qualitative assessment when justified, but tries to limit legal risk
            and administrative burden. It further requires guarantees, compliance
            checks, and penalties for non-compliance, including possible removal
            of support or exclusion from future auctions.

            What it means for bidders:
            A bidder is no longer just competing on price. Depending on the
            tender design, the bidder may have to show due-diligence practices, a
            cybersecurity plan, delivery readiness documents, origin/component
            evidence for resilience, lifecycle data for carbon footprint, product
            information for circularity or efficiency, and environmental measures
            related to biodiversity or water. In other words, this act pushes
            tender preparation much closer to structured evidence-based project
            readiness.

            Offshore wind relevance:
            This regulation is extremely important for offshore wind because it
            gives legal tools for dealing with some of the hardest offshore
            issues: supply-chain concentration, biodiversity and marine
            protection, water-related impact, major component origin, and the
            maturity and deliverability of large complex projects. For offshore
            projects, this is the most useful EU text after NZIA itself.

            Common misunderstanding:
            Many people say 2025/1176 "contains 12 KPIs" as if it is a simple
            checklist. That is partly true, but not complete. The regulation does
            more than list categories. It also tells you how authorities should
            assess them, when external legislation should be used, how compliance
            should be verified, and how penalties should work. So it is both a
            KPI framework and an auction-governance text.

            Why you should read it closely:
            For thesis work, this is the main law for translating legal language
            into toolbox logic, user inputs, scoring structures, readiness
            checks, and evidence requirements.
            """,
            ["https://eur-lex.europa.eu/eli/reg_impl/2025/1176/oj/eng"],
        ),
        "3": Topic(
            "Commission Implementing Regulation (EU) 2025/1178",
            """
            What it is:
            This is the companion resilience regulation. It does not create new
            KPI families and it does not replace NZIA or Regulation 2025/1176.
            Its role is narrower but very important: it supplies the list of
            final products and main specific components that matter when the
            resilience criterion is applied.

            Main purpose:
            The purpose is to make resilience legally operational. Resilience
            sounds simple in policy language, but in practice an authority needs
            to know exactly which products and which major components must be
            checked. Otherwise the rule becomes vague and hard to enforce. This
            regulation solves that problem by setting out the relevant list in an
            annex.

            How it works:
            The regulation states that the list of net-zero technology final
            products and their main specific components for assessing resilience
            is set out in the annex. It also clarifies why those components were
            selected: they are considered essential either because they
            contribute significantly to final product value or because they are
            critical to the resilience of the supply chain.

            Why it matters for auctions:
            Once resilience rules in NZIA and 2025/1176 ask whether a final
            product or a main specific component originates in a certain third
            country, authorities need a legally fixed reference point. This act
            becomes that reference point. It therefore turns resilience from a
            political idea into an administratively usable test.

            Offshore wind relevance:
            Offshore wind is one of the clearest examples of why this law matters.
            The annex lists offshore wind turbines and major components such as
            nacelles, rotor hubs, bearings, drivetrains or gearboxes, blades,
            towers, and foundations or floaters. That means resilience checks in
            offshore tenders can be applied to specific parts of the turbine and
            project supply chain, not just to the final project in the abstract.

            Timing point:
            The regulation entered into force after publication and applies from
            30 December 2025. That timing matters because it gave Member States a
            preparation period before the resilience contribution became fully
            operational in practice.

            Common misunderstanding:
            Some users think this act is "small" and therefore less important.
            In reality, it is a technical key. Without it, resilience would be
            much harder to verify consistently across Member States and across
            technologies.

            Why you should keep it in your toolbox:
            Whenever resilience is discussed in a serious way, this regulation is
            the document that tells you exactly what must be checked.
            """,
            ["https://eur-lex.europa.eu/eli/reg_impl/2025/1178/oj/eng"],
        ),
    },
    "2": {
        "1": Topic(
            "Directive (EU) 2018/2001 — Renewable Energy Directive (RED / RED III)",
            """
            What it is:
            RED is the broader EU framework for promoting renewable energy. It is
            not a non-price KPI law in the same direct way as NZIA and 2025/1176,
            but it governs the legal architecture in which renewable support
            schemes and tenders operate.

            Main purpose:
            Its purpose is to increase renewable energy deployment while keeping
            support schemes compatible with internal-market principles and with
            long-term investment certainty. It is a framework law for renewable
            energy growth rather than a detailed KPI manual.

            Why it matters for auction design:
            RED requires support schemes to be market-based, market-responsive,
            open, transparent, competitive, non-discriminatory, and
            cost-effective. That means Member States cannot simply invent tender
            rules that are politically attractive but legally unstable. Even when
            non-price criteria are used, the wider structure of the auction still
            has to respect RED's discipline.

            Practical legal effect:
            RED influences qualification rules, publication requirements, bidding
            transparency, and the overall design of support schemes. It also
            pushes Member States toward clear and predictable frameworks instead
            of ad hoc or unstable intervention. This is especially important for
            large capital-intensive technologies such as offshore wind.

            Relationship with NZIA:
            A useful way to think about it is this: NZIA tells Member States that
            certain non-price criteria must be included in part of renewable
            auctions. RED tells them that the whole support scheme still has to
            remain open, transparent, competitive, and cost-effective. So RED is
            part of the legal boundary around NZIA implementation.

            Offshore wind relevance:
            Offshore auctions are often multi-year, highly capital-intensive, and
            dependent on predictable support design. RED matters here because
            investors care not only about the existence of non-price criteria but
            also about whether the auction system is stable, transparent, and
            consistent with broader EU renewable support principles.

            Common misunderstanding:
            A common mistake is to treat RED as background law with no impact on
            KPI design. In reality, it strongly shapes the legal room in which
            KPI-based tender design is allowed to operate.
            """,
            ["https://eur-lex.europa.eu/eli/dir/2018/2001/oj/eng"],
        ),
        "2": Topic(
            "Electricity market reform — Regulation (EU) 2019/943, Regulation (EU) 2024/1747, Directive (EU) 2024/1711",
            """
            What it is:
            This package is the part of EU electricity-market law that matters
            for how renewable support is structured. It becomes especially
            relevant when tenders are linked to direct price-support schemes such
            as two-way contracts for difference, also called two-way CfDs.

            Main purpose:
            Its purpose is to make the electricity market more stable, improve
            consumer protection, reduce exposure to extreme price volatility, and
            give investors a clearer long-term revenue framework without
            distorting competition more than necessary.

            Why it matters for renewable tenders:
            Many renewable tenders are not only about who wins the site or the
            support budget. They also decide the support format. Article 19d of
            the amended Electricity Regulation says that direct price-support
            schemes for investment in new power-generating facilities from the
            listed renewable sources must take the form of two-way CfDs or
            equivalent schemes with the same effects.

            Practical meaning:
            This is not a KPI law by itself. It does not define the 12 non-price
            KPI families. But it strongly shapes how price and non-price criteria
            live together inside the same auction. A tender may have non-price
            award criteria because of NZIA, but it may also be built around a
            support mechanism whose legal structure is controlled by electricity
            market law.

            Offshore wind relevance:
            This matters a lot in offshore wind because offshore projects often
            depend on revenue-stabilising support schemes due to their scale,
            capital intensity, and financing needs. Offshore hybrid assets also
            have specific timing treatment under the reform package, which shows
            that the law is sensitive to the particular structure of some
            offshore projects.

            Relationship with other laws:
            A useful way to think about it is that RED shapes the support-scheme
            framework, electricity-market reform shapes the support instrument,
            and NZIA plus 2025/1176 shape the non-price layer. In real tenders,
            all of these can operate at the same time.

            Common misunderstanding:
            People sometimes ignore this package because it is "about price" and
            not "about KPIs." But for real tender design that is a mistake.
            Support-format law can strongly affect how easily non-price criteria
            can be integrated and financed.
            """,
            [
                "https://eur-lex.europa.eu/eli/reg/2019/943/oj/eng",
                "https://eur-lex.europa.eu/eli/reg/2024/1747/oj/eng",
                "https://eur-lex.europa.eu/eli/dir/2024/1711/oj/eng",
            ],
        ),
        "3": Topic(
            "CEEAG 2022 — Guidelines on State aid for climate, environmental protection and energy",
            """
            What it is:
            CEEAG is not a regulation or directive. It is the Commission's State
            aid compatibility framework for climate, environmental protection,
            and energy measures. Even though it is sometimes treated as a
            secondary document, it is one of the most important hidden legal
            constraints in renewable tender design.

            Main purpose:
            Its purpose is to ensure that public support is necessary,
            proportionate, and compatible with the internal market, while still
            allowing Member States to support decarbonisation and environmental
            objectives.

            Why it matters for non-price criteria:
            CEEAG says competitive bidding should be open, clear, transparent and
            non-discriminatory, based on objective criteria defined ex ante and
            published sufficiently far in advance. It also says that the ranking
            criteria should as a general rule relate directly or indirectly to
            the main objective of the measure and the aid amount requested.

            The important weighting point:
            CEEAG also says that if a Member State includes other selection
            criteria that are not directly or indirectly related to the main
            objective of the measure, those other criteria must account for not
            more than 30 percent of the weighting of all selection criteria, and
            the Member State must justify that approach. This is one of the key
            reasons why non-price criteria need to be designed very carefully.

            Practical meaning:
            Even if NZIA allows or requires non-price criteria, the tender may
            still need to survive State aid scrutiny. So a Member State cannot
            simply add broad social or industrial preferences without checking
            whether they fit the State aid logic of necessity, proportionality,
            and objective connection to the measure.

            Offshore wind relevance:
            Offshore tenders often involve large support volumes and therefore
            attract especially strong scrutiny. In such cases, the real legal
            space for non-price criteria often sits in the overlap between NZIA,
            RED, electricity-market rules, and CEEAG.

            Common misunderstanding:
            A lot of people talk about non-price tender design as if NZIA alone
            controls it. In practice, CEEAG often decides how far the design can
            go without creating State aid problems.

            Why this text is strategically important:
            If NZIA is the political door that opens non-price auctions, CEEAG is
            often the legal filter that decides which auction designs are robust
            enough to survive review.
            """,
            ["https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52022XC0218(03)"],
        ),
        "4": Topic(
            "Procurement and concession directives — Directives 2014/24/EU, 2014/25/EU, and 2014/23/EU",
            """
            What they are:
            These are the EU's main legal instruments for public procurement,
            utility procurement, and concession awards. They matter whenever the
            legal vehicle is not a pure State-aid auction, but a public contract,
            utility-sector procurement, or concession-type structure.

            Main purpose:
            Their purpose is to ensure transparency, equal treatment,
            non-discrimination, and effective competition when public authorities
            or utilities buy goods, works, services, or grant concession rights.

            Why they matter for non-price criteria:
            These directives allow contracts to be awarded on the basis of the
            most economically advantageous tender, not only the lowest price.
            That creates legal room for quality, environmental, social, and
            innovation-related considerations, provided the criteria are linked
            to the subject matter and applied in an objective, transparent way.

            Practical meaning:
            If a Member State structures part of an offshore project through a
            procurement route rather than a classic renewable support auction,
            these directives become highly relevant. They can support broader
            best-price-quality approaches, but they also impose discipline:
            criteria must be clear, published, and applied consistently.

            Offshore wind relevance:
            Offshore projects can involve seabed rights, grid connections,
            infrastructure works, concession structures, public entities, and
            utility participation. Because of that complexity, offshore legal
            frameworks may sometimes touch procurement and concession law in
            addition to energy-support law.

            What this means for users:
            If you are analysing an offshore tender, you should always ask one
            legal question first: is this purely a support auction, or is there
            also a procurement or concession element? The answer can change which
            legal toolbox applies.

            Common misunderstanding:
            People often assume renewable tenders are always pure energy-law
            processes. That is not always true. In some structures, procurement
            or concession law is part of the legal backbone and can influence how
            non-price criteria are framed and defended.
            """,
            [
                "https://eur-lex.europa.eu/eli/dir/2014/24/oj/eng",
                "https://eur-lex.europa.eu/eli/dir/2014/25/oj/eng",
                "https://eur-lex.europa.eu/eli/dir/2014/23/oj/eng",
            ],
        ),
    },
    "3": {
        "1": Topic(
            "Responsible business conduct",
            """
            What this KPI is really about:
            Responsible business conduct is not just a soft ethics statement. In
            the EU tender context it is a governance and due-diligence criterion.
            The idea is that a bidder should show it has serious procedures for
            identifying, preventing, mitigating, and communicating about harmful
            impacts in its business activities related to the auction.

            Main legal sources:
            The most important feeder laws are the Corporate Sustainability Due
            Diligence Directive, the Accounting Directive, the Corporate
            Sustainability Reporting Directive, and the European Sustainability
            Reporting Standards. Regulation 2025/1176 also points to relevant
            international frameworks such as the UN Guiding Principles and OECD
            due-diligence standards.

            How 2025/1176 uses those laws:
            Article 4 says that, with some lighter treatment for certain smaller
            actors and renewable energy communities, bidders should take action on
            the core elements of due diligence referred to in Article 5(1)(a) to
            (g) of the CSDDD. In simple terms, that means this KPI is linked to
            due-diligence systems, not just general CSR language.

            What authorities may ask for:
            Authorities may ask for a public statement covering the relevant due-
            diligence elements and, for companies in scope, supporting statements
            assured by independent third parties. Smaller actors can face lighter
            reporting requirements, especially below certain project-size
            thresholds, but the core logic remains the same: the bidder must show
            that responsible business conduct is real and documented.

            What this means in practice:
            A serious bidder should be ready to show that responsible business
            conduct is embedded in policy, monitoring, communication, and
            management systems. This can include due-diligence policies, risk
            identification, mitigation procedures, complaints or grievance logic,
            follow-up monitoring, and public communication.

            Why it matters in tenders:
            The EU is trying to avoid a situation where renewable deployment is
            accelerated while social, human-rights, or supply-chain governance
            risks are ignored. This KPI says that access to renewable auction
            opportunities should increasingly depend on credible business conduct,
            not only on technical or financial strength.

            Offshore wind relevance:
            Offshore wind projects often depend on large supply chains, major
            manufacturing contracts, cross-border sourcing, and subcontracting.
            That makes governance and due diligence more important, not less.

            Common misunderstanding:
            This KPI is sometimes treated as a vague ESG bonus. That is not the
            right reading. In the regulation, it functions as a real
            pre-qualification criterion tied to corporate due-diligence and
            sustainability-reporting law.
            """,
            [
                "https://eur-lex.europa.eu/eli/dir/2024/1760/oj/eng",
                "https://eur-lex.europa.eu/eli/dir/2013/34/oj/eng",
                "https://eur-lex.europa.eu/eli/dir/2022/2464/oj/eng",
                "https://eur-lex.europa.eu/eli/reg_del/2023/2772/oj/eng",
                "https://eur-lex.europa.eu/eli/reg_impl/2025/1176/oj/eng",
            ],
        ),
        "2": Topic(
            "Cybersecurity and data security",
            """
            What this KPI is really about:
            This KPI is about the security of critical renewable energy
            infrastructure as a digital and operational system. It is not only
            about IT hygiene. It is about whether the project can be built and
            operated in a way that protects network and information systems,
            preserves control over operations, and reduces strategic cyber risk.

            Main legal sources:
            The central feeder law is NIS2. An adjacent but broader law is the
            Critical Entities Resilience Directive. Regulation 2025/1176 takes
            ideas from those frameworks and uses them in the renewable-auction
            context.

            How 2025/1176 uses those laws:
            Article 5 requires appropriate and proportionate technical,
            operational, and organisational measures based on security by design
            and by default. It also points to the types of measures listed in
            Article 21(2) of NIS2, which is important because it links the KPI to
            a recognised EU cybersecurity framework rather than leaving it vague.

            Sensitive-case logic:
            The regulation goes further in cases involving risky third-country
            exposure. In certain circumstances it requires a cybersecurity plan
            that explains how the bidder protects the installation and the system,
            how relevant data are stored in the EEA and not transferred outside
            it, how suppliers follow similar measures, and how an operator
            established in the EEA maintains operational control of the
            installation.

            What authorities may ask for:
            Authorities can require a cybersecurity plan and updates to it during
            project implementation. That means this criterion is not just checked
            once at bid stage; it can continue to matter during the life of the
            project.

            Why it matters in tenders:
            The EU is recognising that renewable energy assets are critical
            infrastructure. A large offshore wind farm is not only a power asset.
            It is also a digitally managed system with remote connections,
            software dependencies, data flows, grid integration, and suppliers of
            ICT products and services. That makes cyber risk part of tender
            quality, not only an operational afterthought.

            Offshore wind relevance:
            This KPI is especially important offshore because offshore assets rely
            heavily on remote supervision, communications, control systems,
            predictive maintenance, and grid-critical coordination. Cybersecurity
            failures can therefore create both infrastructure and energy-security
            risks.

            Common misunderstanding:
            Some users think this KPI only matters for very high-tech digital
            firms. In reality, it matters for mainstream renewable developers too,
            because modern renewable projects are deeply digital infrastructures.
            """,
            [
                "https://eur-lex.europa.eu/eli/dir/2022/2555/oj/eng",
                "https://eur-lex.europa.eu/eli/dir/2022/2557/oj/eng",
                "https://eur-lex.europa.eu/eli/reg_impl/2025/1176/oj/eng",
            ],
        ),
        "3": Topic(
            "Ability to deliver fully and on time",
            """
            What this KPI is really about:
            This criterion is the EU's answer to speculative bidding and weakly
            prepared projects. Its purpose is to ensure that a project winner is
            not just cheap on paper, but actually able to complete the project.

            Main legal source:
            The key source is Article 6 of Implementing Regulation 2025/1176.
            Unlike some of the other KPIs, this one is not mostly borrowed from a
            broad external legislation family. It is more directly built as an
            auction-discipline tool.

            What the regulation allows authorities to request:
            Authorities may require two or more documents from a list that
            includes bidder identification, permit-related documentation,
            evidence of financial capability, project description, technical
            feasibility and experience, and a construction and operation
            timetable with key intermediate steps.

            Why this matters:
            The criterion tries to stop a common policy failure in renewable
            auctions: projects that win aggressively but later fail to reach
            financial close, fail to obtain permits, fail to build on time, or
            delay deployment because they were never truly mature. This is one of
            the clearest examples of the EU pushing auctions toward realistic,
            executable projects.

            Flexibility of the requirement:
            The regulation also says the requirements should be modulated
            depending on project cost, risk, capacity, technology maturity, the
            degree of innovation, and other market conditions. That is important
            because it means the law is not trying to impose a one-size-fits-all
            readiness test on every technology and every auction.

            What this means for bidders:
            Bidders need to think beyond price and ask whether they can document
            project maturity in a way that survives scrutiny. Financial capacity,
            permitting status, technical track record, and scheduling discipline
            become part of competitive positioning.

            Offshore wind relevance:
            This is especially important in offshore wind because offshore
            projects are large, expensive, logistically complex, heavily
            permitted, and vulnerable to delay. The delivery-readiness criterion
            therefore has major practical relevance in offshore tenders.

            Common misunderstanding:
            This criterion is sometimes seen as boring compared with resilience or
            sustainability. In reality, it is one of the most important criteria
            for protecting execution rates and deployment speed.
            """,
            ["https://eur-lex.europa.eu/eli/reg_impl/2025/1176/oj/eng"],
        ),
        "4": Topic(
            "Resilience",
            """
            What this KPI is really about:
            Resilience in this context is mainly about strategic supply-chain
            dependency. It asks whether the Union is too dependent on one third
            country for final products or major components used in net-zero
            technologies. So resilience here is not just physical robustness of
            the project. It is market-access policy aimed at reducing excessive
            concentration.

            Main legal chain:
            The key legal chain is NZIA Article 26, Implementing Regulation
            2025/1176, Implementing Regulation 2025/1178, and the Union Customs
            Code for country-of-origin rules. The broader Critical Raw Materials
            Act is not the auction rule itself, but it belongs to the same EU
            strategic-dependency agenda.

            Threshold logic:
            Article 7 of Regulation 2025/1176 says that if the Commission has
            determined that more than 50 percent of Union supply of certain
            final products comes from a single third country, or that supply from
            one third country has risen by at least 10 percentage points on
            average for two consecutive years and reaches at least 40 percent,
            then authorities must use resilience conditions in the auction.

            Offshore wind-specific rule:
            For offshore wind technologies, the regulation says the final
            products must not originate in that third country and no more than
            four main specific components may originate there. It also says that
            direct-drive drivetrains including generator, or gearbox drivetrains
            including generator, must not originate in that third country. This
            is one of the clearest examples of a legal rule being translated into
            component-level supply-chain constraints.

            Additional component logic:
            Where one or more main specific components are themselves heavily
            concentrated, the regulation allows or requires additional component
            quantity limits. In some cases, if concentration is extremely high,
            the applicable thresholds can be adjusted within the legal range
            described in the act.

            China-specific fallback:
            The regulation also includes a special fallback for onshore wind,
            offshore wind, and electrolysers. Even where the Commission has not
            yet formally determined excessive overall concentration, authorities
            must still apply the resilience criterion in relation to final
            products and components originating or assembled in the People's
            Republic of China for at least 75 percent of the final products in
            the bid. This shows how politically important resilience has become.

            Evidence and verification:
            Compliance is not based only on declaration. Authorities may require
            customs documentation and other relevant documents proving origin or
            place of assembly, including invoices and similar evidence. This is
            why the customs-origin framework matters directly to auction design.

            Offshore wind relevance:
            Resilience is arguably one of the most politically sensitive KPIs in
            offshore wind because offshore projects rely on complex, global,
            component-heavy supply chains and because Europe is trying to rebuild
            industrial strength without stopping deployment.

            Common misunderstanding:
            A common mistake is to think resilience is vague industrial policy.
            In the current EU framework it is increasingly specific, component-
            based, and evidence-driven.
            """,
            [
                "https://eur-lex.europa.eu/eli/reg/2024/1735/oj/eng",
                "https://eur-lex.europa.eu/eli/reg_impl/2025/1176/oj/eng",
                "https://eur-lex.europa.eu/eli/reg_impl/2025/1178/oj/eng",
                "https://eur-lex.europa.eu/eli/reg/2013/952/oj/eng",
                "https://eur-lex.europa.eu/eli/reg/2024/1252/oj/eng",
            ],
        ),
        "5": Topic(
            "Carbon footprint, circular economy, energy efficiency, and pollution",
            """
            What these KPI families are really about:
            These criteria turn renewable tenders away from a narrow "lowest
            upfront price" mindset and toward lifecycle performance. Instead of
            asking only how much the project costs, the law asks what the
            technology looks like across production, use, maintenance,
            decommissioning, resource use, recyclability, and environmental
            footprint.

            Carbon footprint:
            Article 8 of Regulation 2025/1176 requires authorities to indicate
            the net-zero technologies whose carbon footprint must be assessed and
            the methodology used. Bidders must measure and communicate carbon
            footprint using binding Union lifecycle methods where those exist. If
            no specific method exists, the regulation still requires life-cycle
            coverage at least across resource extraction and transport,
            manufacturing, energy used in production, transport of components and
            final products, installation, operation and maintenance, and end of
            life.

            Circular economy:
            Article 9 says authorities can assess parameters such as
            recyclability, ease of repair and maintenance, upgradeability, reuse,
            remanufacturing, refurbishment, and recycled-material content,
            including critical raw materials. This is strongly linked to the
            logic of the Ecodesign for Sustainable Products Regulation.

            Energy efficiency:
            Article 11 says energy efficiency must be assessed using methods from
            Union legislation where available. Where products fall under the
            Energy Labelling Regulation or related acts, the relevant criteria
            should follow that framework. Where that is not available, other
            Union methods or international standards can be used.

            Pollution:
            Article 13 lets authorities assess contributions to reducing
            pollution other than greenhouse gases during installation, operation,
            and decommissioning. Relevant methods, thresholds, and compliance
            mechanisms should be based on Union law where available, including
            taxonomy-related references where relevant.

            Why feeder laws matter:
            These KPI families borrow heavily from product and lifecycle law,
            including ESPR, the Energy Labelling Regulation, the older Ecodesign
            Directive framework, taxonomy-related methodology, and in some
            contexts the Batteries Regulation. So the auction regulation is not
            inventing all methods by itself; it is drawing on wider EU product
            sustainability law.

            Why this matters in tenders:
            These criteria make it legally possible to value technologies that
            are better over the full lifecycle, not just cheaper at bid stage.
            That can matter a lot where Europe wants to reward lower lifecycle
            emissions, better circularity, higher efficiency, or lower non-GHG
            pollution.

            Offshore wind relevance:
            In offshore wind, these criteria can matter for large components,
            marine operations, maintenance strategies, and end-of-life treatment.
            They help move the discussion from capex only to longer-term
            environmental and resource performance.

            Common misunderstanding:
            Some users treat these as purely environmental add-ons. In reality,
            they are also industrial quality criteria because they influence how
            durable, repairable, efficient, and strategically sustainable the
            technology is.
            """,
            [
                "https://eur-lex.europa.eu/eli/reg_impl/2025/1176/oj/eng",
                "https://eur-lex.europa.eu/eli/reg/2024/1781/oj/eng",
                "https://eur-lex.europa.eu/eli/reg/2017/1369/oj/eng",
                "https://eur-lex.europa.eu/eli/dir/2009/125/oj/eng",
                "https://eur-lex.europa.eu/eli/reg_del/2023/2486/oj/eng",
                "https://eur-lex.europa.eu/eli/reg/2023/1542/oj/eng",
            ],
        ),
        "6": Topic(
            "Biodiversity, water, and offshore environmental performance",
            """
            What these KPI families are really about:
            This is where renewable tender law connects most directly to classic
            EU environmental law. In offshore wind, this area is especially
            important because projects directly affect marine habitats, birds,
            seabed conditions, underwater noise, and water status.

            Biodiversity:
            Article 10 of Regulation 2025/1176 allows authorities to assess the
            biodiversity impact of a project during installation, operation, and
            decommissioning. As a pre-qualification criterion, the regulation
            expects a system to monitor positive and negative biodiversity
            effects and commitments to adaptive solutions that avoid negative
            impacts and support positive impacts where relevant.

            Award-stage biodiversity logic:
            When biodiversity is used as an award criterion, the regulation goes
            further and can ask for positive contributions beyond compliance. It
            explicitly links this to environmental objectives in wider EU law,
            including the Habitats Directive, the Birds Directive, the Nature
            Restoration Regulation, the Marine Strategy Framework Directive for
            offshore installations, and the Water Framework Directive.

            Water:
            Article 12 allows authorities to assess how project operation helps
            preserve and, where applicable, improve the status of water bodies.
            It requires monitoring of water impacts and adaptive solutions to
            avoid negative effects. Where water is used as an award criterion,
            the law expects positive contributions toward good water quality and
            quantity under the Water Framework Directive.

            Pollution:
            Article 13 complements biodiversity and water by allowing authorities
            to assess reductions in pollution other than greenhouse gases during
            installation, operation, and decommissioning. This can be highly
            relevant offshore, where the environmental discussion goes beyond
            carbon and includes marine disturbance and local ecological effects.

            Why the external environmental laws matter:
            These feeder laws provide the substantive environmental objectives.
            The auction regulation does not replace environmental law. Instead,
            it uses existing environmental goals and monitoring logic as content
            for tender criteria.

            Offshore wind relevance:
            This is arguably the clearest place where offshore specificity enters
            the EU KPI framework. Offshore projects interact with the marine
            environment in a way that onshore projects often do not. As a result,
            biodiversity, marine status, and water-related considerations can
            become central to non-price evaluation.

            Common misunderstanding:
            These criteria are not simply about proving legal compliance with EIA
            or habitat law. The regulation allows Member States to go further and
            reward projects that contribute positively beyond minimum legal
            requirements.
            """,
            [
                "https://eur-lex.europa.eu/eli/reg_impl/2025/1176/oj/eng",
                "https://eur-lex.europa.eu/eli/dir/1992/43/oj/eng",
                "https://eur-lex.europa.eu/eli/dir/2009/147/oj/eng",
                "https://eur-lex.europa.eu/eli/reg/2024/1991/oj/eng",
                "https://eur-lex.europa.eu/eli/dir/2008/56/oj/eng",
                "https://eur-lex.europa.eu/eli/dir/2000/60/oj/eng",
            ],
        ),
    },
    "4": {
        "1": Topic(
            "Maritime Spatial Planning Directive 2014/89/EU",
            """
            What it is:
            This directive requires Member States to organise maritime space in a
            structured way. It is not a tender-scoring law, but it is a basic
            offshore-development law because it influences where offshore
            projects can realistically be located.

            Main purpose:
            Its purpose is to reduce conflict between different uses of the sea
            such as offshore energy, shipping, fisheries, environmental
            protection, defence, and coastal activities. It also tries to improve
            coherence between maritime spatial planning and other planning
            processes.

            Why it matters before the tender starts:
            A tender can only exist if there is a site, a planning framework, and
            some legal logic for coexistence with other sea users. Maritime
            spatial planning therefore shapes site availability, constraints,
            conflict management, and sometimes even the likely environmental and
            grid conditions of a future tender area.

            Practical meaning:
            The directive requires Member States to take account of land-sea
            interactions, environmental, economic, and social aspects, safety,
            stakeholder involvement, and the use of the best available data. That
            makes it part of the upstream legal structure of offshore project
            development.

            Offshore wind relevance:
            For offshore wind, this law is crucial because it affects which areas
            are prioritised, how competing interests are balanced, and whether
            environmental or navigation constraints are already shaping the
            project before auction design even begins.

            Common misunderstanding:
            It is easy to ignore this law because it does not mention tender
            scores or KPIs. But in offshore wind it is one of the hidden laws
            that quietly determines the real development space in which tenders
            later operate.
            """,
            ["https://eur-lex.europa.eu/eli/dir/2014/89/oj/eng"],
        ),
        "2": Topic(
            "SEA Directive 2001/42/EC and EIA Directive 2011/92/EU",
            """
            What they are:
            SEA is the strategic environmental assessment regime for plans and
            programmes. EIA is the environmental impact assessment regime for
            individual projects. Together they form the core environmental-
            assessment backbone of infrastructure planning in Europe.

            Main purpose:
            Their purpose is to ensure environmental impacts are identified,
            assessed, and taken into account before decisions are finalised.
            SEA deals with the strategic planning level; EIA deals with the
            project-specific authorisation level.

            Why they matter for offshore tenders:
            Offshore tenders often sit on top of planning and permitting systems
            that have already been shaped by SEA and EIA. That means site
            selection, environmental constraints, mitigation obligations,
            consultation requirements, and permitting risk are often influenced
            long before the auction itself takes place.

            Relationship with non-price KPIs:
            These directives do not create the non-price KPI framework, but they
            are closely linked to its environmental content. Biodiversity, water,
            and offshore environmental performance criteria in the auction
            context make much more sense when read together with the broader
            assessment system created by SEA and EIA.

            Offshore wind relevance:
            In offshore wind, these laws are especially important because marine
            ecosystems are sensitive, project footprints are large, and
            transboundary or cumulative impacts may matter. The environmental
            profile of the site and of the project is therefore often shaped by
            these directives before any non-price scoring logic is applied.

            Common misunderstanding:
            Some users think SEA and EIA are only permitting issues. In reality,
            they can strongly influence tender design because they affect site
            maturity, environmental obligations, timeline risk, and the types of
            mitigation or enhancement measures that later become relevant in
            non-price criteria.
            """,
            [
                "https://eur-lex.europa.eu/eli/dir/2001/42/oj/eng",
                "https://eur-lex.europa.eu/eli/dir/2011/92/oj/eng",
            ],
        ),
        "3": Topic(
            "Offshore Renewable Energy Strategy and European Wind Power Action Plan",
            """
            What they are:
            These are European Commission policy communications, not binding
            regulations or directives. They therefore do not impose the same kind
            of direct legal obligations as NZIA or 2025/1176.

            Why they still matter:
            Even though they are not binding law, they are highly useful for
            understanding policy direction. They explain why the EU has become
            more focused on offshore scale-up, supply-chain bottlenecks,
            manufacturing capacity, resilience, permitting acceleration, and
            investment support.

            Offshore Renewable Energy Strategy:
            The offshore strategy sets the broader political vision for scaling
            offshore renewable energy in Europe. It helps explain why offshore is
            seen not only as an energy source but also as a strategic industrial
            and infrastructure area requiring long-term coordination.

            European Wind Power Action Plan:
            The wind action plan is especially useful for understanding the
            immediate political concerns around the wind sector: supply-chain
            stress, project delays, financing, permitting, grid issues, and the
            need to strengthen European industrial capacity. It helps explain why
            later legal acts place more emphasis on resilience, deliverability,
            and industrial support.

            Why this matters for thesis work:
            These documents are good for policy background sections. They can help
            explain the story behind the law: why Europe moved from purely
            cost-focused auctions toward frameworks that also care about
            resilience, sustainability, quality, and execution.

            Common misunderstanding:
            They are often cited as if they were legal obligations. That is not
            correct. Their main value is interpretive and contextual. They tell
            you where EU policy is heading, but not by themselves what a tender
            authority is legally required to do.
            """,
            [
                "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52020DC0741",
                "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52023DC0669",
            ],
        ),
    },
    "5": {
        "1": Topic(
            "Industrial Decarbonisation Accelerator Act / Industrial Accelerator Act",
            """
            What it is:
            This is a future-oriented EU industrial policy initiative associated
            with the Clean Industrial Deal. The Commission presented it in March
            2026 as part of a wider push to strengthen demand for low-carbon and
            European-made technologies and products.

            Main purpose:
            Its purpose is broader than renewable tender KPIs. It aims to support
            industrial decarbonisation, clean manufacturing, strategic demand,
            and competitiveness. In public-policy terms, it belongs to the wider
            EU move toward combining climate action with industrial strategy.

            Why it matters:
            The initiative is important for understanding where EU policy may go
            next. It suggests stronger use of public procurement and public
            support schemes to create demand for low-carbon and European-made
            products, which means it could become relevant to future debates on
            resilience and sustainability conditions.

            Why it is not the current core law for your topic:
            For a thesis on current non-price criteria in renewable tenders, this
            is not the main binding legal base. The present legal core remains
            NZIA plus Implementing Regulation 2025/1176, supported by 2025/1178
            and the wider architecture of RED, State aid rules, and sectoral
            feeder laws.

            How to use it in thesis work:
            Use this act for a future outlook or policy-development subsection.
            It can help you discuss where EU industrial and procurement policy
            may move next, especially on resilience and demand-side support. But
            it should not replace the current binding auction framework in your
            legal analysis.

            Common misunderstanding:
            Because it sounds highly relevant, people sometimes assume it is
            already the law that governs renewable tender KPIs. That is not the
            right interpretation. At the moment, it is part of the future-facing
            industrial policy agenda, not the central present legal source for
            renewable-auction KPI design.
            """,
            [
                "https://commission.europa.eu/topics/competitiveness/clean-industrial-deal_en",
                "https://commission.europa.eu/news-and-media/news/commission-proposes-new-measures-boost-eu-industry-and-jobs-2026-03-04_en",
            ],
        ),
    },
}


def main() -> None:
    while True:
        clear_screen()
        print("=" * WRAP)
        print("EU NON-PRICE KPIs IN RENEWABLE TENDERS — DETAILED THEORY GUIDE")
        print("=" * WRAP)
        print()
        print_block(
            "This guide explains the legal theory behind EU non-price criteria in "
            "renewable tenders, with special attention to offshore wind. "
            "The official legal texts always prevail, but this menu is designed "
            "to help a user understand the structure before reading the original laws."
        )
        print("Choose a section:")
        for key, value in MAIN_MENU.items():
            print(f" {key}. {value}")
        print(" 0. Exit")
        print()

        choice = input("Enter your choice: ").strip()

        if choice == "0":
            clear_screen()
            print("Goodbye.")
            break

        if choice not in SUB_MENUS:
            input("Invalid option. Press Enter to continue...")
            continue

        while True:
            clear_screen()
            print("=" * WRAP)
            print(MAIN_MENU[choice])
            print("=" * WRAP)
            print()
            print_block(SECTION_INTROS[choice])
            for key, value in SUB_MENUS[choice].items():
                print(f" {key}. {value}")
            print(" 0. Back")
            print()

            sub_choice = input("Enter your choice: ").strip()

            if sub_choice == "0":
                break

            topic = TOPICS.get(choice, {}).get(sub_choice)
            if topic is None:
                input("Invalid option. Press Enter to continue...")
                continue

            print_topic(topic)


if __name__ == "__main__":
    main()